import HomepageInteractive from './components/HomepageInteractive';

export const metadata = {
  title: 'Blinno Marketplace - Shop Authentic Tanzanian Products',
  description: 'Discover authentic Tanzanian products from verified local vendors. Shop electronics, fashion, crafts, and more with secure M-Pesa & Tigo Pesa payments. Fast nationwide delivery.',
  keywords: 'Tanzania marketplace, online shopping Tanzania, M-Pesa shopping, Tanzanian products, African crafts, electronics Tanzania',
  openGraph: {
    title: 'Blinno Marketplace - Tanzania\'s Leading Online Marketplace',
    description: 'Shop authentic products from verified Tanzanian vendors with secure mobile money payments',
    type: 'website',
    locale: 'en_TZ',
  },
};

export default function HomePage() {
  // Mock data for the homepage - In production, this would come from Supabase
  const mockData = {
    categories: [
      {
        id: '1',
        name: 'Electronics',
        slug: 'electronics',
        icon: '📱',
        count: 1250,
      },
      {
        id: '2',
        name: 'Fashion',
        slug: 'fashion',
        icon: '👗',
        count: 2840,
      },
      {
        id: '3',
        name: 'Home & Living',
        slug: 'home-living',
        icon: '🏠',
        count: 1580,
      },
      {
        id: '4',
        name: 'Beauty',
        slug: 'beauty',
        icon: '💄',
        count: 920,
      },
      {
        id: '5',
        name: 'Groceries',
        slug: 'groceries',
        icon: '🛒',
        count: 3200,
      },
      {
        id: '6',
        name: 'Crafts',
        slug: 'crafts',
        icon: '🎨',
        count: 680,
      },
    ],

    featuredProducts: [
      {
        id: 'prod-001',
        name: 'Samsung Galaxy S24 Ultra 256GB',
        category: 'Electronics',
        price: 3200000,
        originalPrice: 3500000,
        discount: 9,
        rating: 5,
        reviews: 234,
        isNew: true,
        image: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600',
      },
      {
        id: 'prod-002',
        name: 'Handwoven Tanzanian Basket - Large',
        category: 'Crafts',
        price: 45000,
        rating: 5,
        reviews: 89,
        isNew: false,
        image: 'https://images.unsplash.com/photo-1590736969955-71cc94901144?w=600',
      },
      {
        id: 'prod-003',
        name: 'African Print Kitenge Dress',
        category: 'Fashion',
        price: 85000,
        originalPrice: 120000,
        discount: 29,
        rating: 4,
        reviews: 156,
        isNew: false,
        image: 'https://images.unsplash.com/photo-1590735213920-68192a487bc2?w=600',
      },
      {
        id: 'prod-004',
        name: 'Premium Tanzanian Coffee Beans 1kg',
        category: 'Groceries',
        price: 32000,
        rating: 5,
        reviews: 412,
        isNew: true,
        image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600',
      },
      {
        id: 'prod-005',
        name: 'Maasai Beaded Necklace Set',
        category: 'Fashion',
        price: 55000,
        originalPrice: 70000,
        discount: 21,
        rating: 5,
        reviews: 78,
        isNew: false,
        image: 'https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=600',
      },
      {
        id: 'prod-006',
        name: 'Wooden Coffee Table - Handcrafted',
        category: 'Home & Living',
        price: 280000,
        rating: 4,
        reviews: 45,
        isNew: true,
        image: 'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=600',
      },
      {
        id: 'prod-007',
        name: 'Natural Shea Butter - 500g',
        category: 'Beauty',
        price: 18000,
        originalPrice: 25000,
        discount: 28,
        rating: 4,
        reviews: 267,
        isNew: false,
        image: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=600',
      },
      {
        id: 'prod-008',
        name: 'Wireless Earbuds Pro - Black',
        category: 'Electronics',
        price: 125000,
        originalPrice: 150000,
        discount: 17,
        rating: 4,
        reviews: 189,
        isNew: false,
        image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600',
      },
    ],

    vendors: [
      {
        id: 'vendor-001',
        name: 'Dar Electronics Hub',
        category: 'Electronics & Gadgets',
        logo: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=200',
        rating: 4.9,
        reviews: 567,
        products: 156,
        tier: 'diamond',
      },
      {
        id: 'vendor-002',
        name: 'Arusha Fashion Boutique',
        category: 'Fashion & Clothing',
        logo: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200',
        rating: 4.8,
        reviews: 423,
        products: 289,
        tier: 'platinum',
      },
      {
        id: 'vendor-003',
        name: 'Zanzibar Spice Market',
        category: 'Food & Groceries',
        logo: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=200',
        rating: 4.9,
        reviews: 892,
        products: 198,
        tier: 'gold',
      },
      {
        id: 'vendor-004',
        name: 'Mwanza Crafts Co.',
        category: 'Arts & Crafts',
        logo: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=200',
        rating: 4.7,
        reviews: 234,
        products: 124,
        tier: 'gold',
      },
      {
        id: 'vendor-005',
        name: 'Kilimanjaro Home Decor',
        category: 'Home & Living',
        logo: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=200',
        rating: 4.8,
        reviews: 345,
        products: 87,
        tier: 'platinum',
      },
      {
        id: 'vendor-006',
        name: 'Dodoma Beauty Haven',
        category: 'Beauty & Personal Care',
        logo: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=200',
        rating: 4.6,
        reviews: 178,
        products: 145,
        tier: 'silver',
      },
    ],
  };

  return <HomepageInteractive initialData={mockData} />;
}

